services:
  redis:
    image: redis:7-alpine
    # Redis is now optional - only needed for caching and metrics
    # The unified worker connects directly to PostgreSQL
    command: redis-server --maxmemory 2gb --maxmemory-policy allkeys-lru --appendonly yes --appendfsync everysec
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  db:
    image: postgres:14
    # Reduced max_connections since we only have 1 worker now (not 32)
    command: postgres -c max_connections=500 -c shared_buffers=20GB -c effective_cache_size=42GB -c work_mem=256MB -c maintenance_work_mem=8GB -c max_parallel_workers=32 -c max_parallel_workers_per_gather=8 -c max_wal_size=8GB
    environment:
      POSTGRES_DB: atproto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data,Z
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d atproto"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    shm_size: 10gb

  # UNIFIED PYTHON WORKER - Replaces 32 TypeScript workers!
  # Single Python process that:
  # - Connects to AT Protocol firehose
  # - Processes events directly to PostgreSQL
  # - No Redis queue needed (but available for caching)
  unified-worker:
    build:
      context: ./python-firehose
      dockerfile: Dockerfile.unified
    environment:
      - RELAY_URL=${RELAY_URL:-wss://bsky.network}
      - DATABASE_URL=postgresql://postgres:password@db:5432/atproto
      - DB_POOL_SIZE=20
      - LOG_LEVEL=INFO
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import asyncpg; import asyncio; asyncio.run(asyncpg.connect('postgresql://postgres:password@db:5432/atproto', timeout=5))\" || exit 1"]
      interval: 30s
      timeout: 10s
      start_period: 40s
      retries: 3
    restart: unless-stopped
    # Resource limits (much lower than 32 workers!)
    deploy:
      resources:
        limits:
          memory: 4G  # Single Python process uses way less than 32 Node.js workers
        reservations:
          memory: 1G

  # Frontend/API server - Lightweight since it's not processing firehose
  app:
    volumes:
      - ./appview-signing-key.json:/app/appview-signing-key.json:ro,Z
      - ./appview-private.pem:/app/appview-private.pem:ro,Z
      - ./public/did.json:/app/public/did.json:ro,Z
      - ./oauth-keyset.json:/app/oauth-keyset.json:ro,Z
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/atproto
      - REDIS_URL=redis://redis:6379
      - SESSION_SECRET=${SESSION_SECRET:-change-this-to-a-random-secret-in-production}
      - APPVIEW_DID=${APPVIEW_DID:-did:web:appview.dollspace.gay}
      - BACKFILL_DAYS=${BACKFILL_DAYS:-0}
      - DATA_RETENTION_DAYS=${DATA_RETENTION_DAYS:-0}
      - DB_POOL_SIZE=50  # Reduced from 200 since no firehose processing
      - PORT=5000
      - NODE_ENV=production
      - OAUTH_KEYSET_PATH=/app/oauth-keyset.json
      - ADMIN_DIDS=did:plc:abc123xyz,admin.bsky.social,did:plc:def456uvw
      - FIREHOSE_ENABLED=false  # Disable TypeScript firehose - Python handles it
      - CONSTELLATION_ENABLED=true
      - CONSTELLATION_URL=https://constellation.microcosm.blue
      - CONSTELLATION_TIMEOUT=15000
      - CONSTELLATION_CACHE_TTL=${CONSTELLATION_CACHE_TTL:-60}
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "node -e \"require('http').get('http://localhost:5000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})\""]
      interval: 30s
      timeout: 10s
      start_period: 40s
      retries: 3
    restart: unless-stopped
    # Resource limits - much lower since it's just serving API/UI
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M

  # Constellation Bridge - Optional enhanced statistics
  constellation-bridge:
    build: ./microcosm-bridge/constellation-client
    environment:
      - CONSTELLATION_URL=${CONSTELLATION_URL:-https://constellation.microcosm.blue}
      - CONSTELLATION_TIMEOUT=5000
      - REDIS_URL=redis://redis:6379
      - CACHE_ENABLED=true
      - CACHE_TTL=${CONSTELLATION_CACHE_TTL:-60}
      - HEALTH_PORT=3003
      - MAX_REQUESTS_PER_SECOND=10
      - USER_AGENT=AppView-Constellation-Bridge/1.0 (@appview.bsky.social)
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "node -e \"require('http').get('http://localhost:3003/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})\""]
      interval: 30s
      timeout: 10s
      start_period: 40s
      retries: 3
    restart: unless-stopped

volumes:
  postgres_data:
