version: '3.8'

services:
  db:
    image: postgres:14
    command: postgres -c max_connections=5000 -c shared_buffers=12GB -c effective_cache_size=36GB -c work_mem=64MB -c maintenance_work_mem=2GB
    environment:
      POSTGRES_DB: atproto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    shm_size: 4gb

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/atproto
      - RELAY_URL=wss://bsky.network
      - SESSION_SECRET=${SESSION_SECRET:-change-this-to-a-random-secret-in-production}
      - DASHBOARD_PASSWORD=${DASHBOARD_PASSWORD:-}
      - APPVIEW_DID=${APPVIEW_DID:-did:web:appview.local}
      - ENABLE_BACKFILL=${ENABLE_BACKFILL:-false}
      - PORT=5000
      - NODE_ENV=production
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "node -e \"require('http').get('http://localhost:5000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})\""]
      interval: 30s
      timeout: 10s
      start_period: 40s
      retries: 3
    restart: unless-stopped

volumes:
  postgres_data:
